name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++

          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
            
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl
            cmake_generator: "Visual Studio 16 2019"
            cmake_arch: "x64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.16.x'

      - name: Install Linux compilers
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang

      - name: Configure CMake (Unix)
        if: runner.os != 'Windows'
        run: cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_install -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_install -G "${{ matrix.cmake_generator }}" -A ${{ matrix.cmake_arch }}

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: cmake --build _build

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build _build --config Release
